[package]
name = "mimirsbrunn"
version = "1.2.0"
authors = ["Canal TP <dt.ro@canaltp.fr>"]
build = "build.rs"
autotests = false
edition = "2018"

[workspace]

[dependencies]
log = { version = "0.4", features = ["release_max_level_debug"] }
slog = { version = "2.4", features = ["max_level_trace", "release_max_level_debug"]}
slog-scope = "4.1"
slog-envlogger = "2.1"
slog-async = "2.3"
structopt = "0.2"
csv = "1"
rs-es = { version = "^0.12.0", features = ["geo"]}
regex = "1"
osmpbfreader = "0.13.2"
chrono = "0.4"
serde = {version = "1", features = ["rc"]}
serde_json = "1"
geo = "0.12"
geo-types = "0.4"
gst = "0.1" # todo remove this dependency in favor of https://github.com/Stoeoef/rstar/blob/master/rstar/
ordered-float = "0.0.2"
itertools = "0.8"
transit_model = "0.5"
osm_boundaries_utils = "0.5"
failure = "0.1"
cosmogony = "0.7"
par-map = "0.1.4"
lazy_static = "1.3"
num_cpus = "1.10"
assert_float_eq = "1"
humanesort = "0.1.0-alpha"
address-formatter = "^0.2.1"
navitia-poi-model = "0.2.0"
walkdir = "2"
rusqlite = "0.20"

mimir = { path = "libs/mimir" }
bragi = { path = "libs/bragi" }

[dev-dependencies]
reqwest = "=0.9.16"
approx = "0.3"
actix-web = "1"
tools = { path = "libs/tools" }
docker_wrapper = { path = "libs/docker_wrapper" }

[build-dependencies]
git-version = "0.2"

# we just call one test method: cf. tests::all_tests()
[[test]]
name = "tests"
